### ISSUE TITLE
This adapter shouldn't work

### ISSUE THREAD

**Issue by mr-tron** [gofiber/adaptor#3]
I didn't check your code direct, but i made some code based on your code and it has bug - not passsing headers to response
In this line
https://github.com/gofiber/adaptor/blob/master/main.go#L74
according to https://golang.org/pkg/net/http/#ResponseWriter

    // Changing the header map after a call to WriteHeader (or
    // Write) has no effect unless the modified headers are
    // trailers.

You should move WriteHeader call to the end

**Comment by Fenny** [comment]
Nice catch @mr-tron, fixed in https://github.com/gofiber/adaptor/releases/tag/v0.1.2 👍

**Comment by mr-tron** [comment]
Also I recommend to use Set() instead Add().

**Comment by Fenny** [comment]
I don't have much time this week, I will accept a PR's if you want to help us ❤️
