### ISSUE TITLE
utils.MemoryTotal undefined error after integrating gofiber adaptor

### ISSUE THREAD

**Issue by vipinzco** [gofiber/adaptor#49]
Hi Team,

In a project which I am currently working on, I have an S3 upload functionality. I have to use the http (w http.ResponseWriter, r *http.Request) along with GoFiber context.

Route:
-----------

v1Auth.Post("/user/uploadProfileImage", adaptor.HTTPHandlerFunc(s.uploadProfileImage))

Function definition
----------------------

`/Upload the profile image to S3 ... user/uploadProfileImage
func (s *Server) uploadProfileImage(c *fiber.Ctx, w http.ResponseWriter, r *http.Request) error {
	user := c.Context().UserValue("userid")
	_, ok := user.(uint32)
	if ok {
		maxSize := int64(3072000) // allow only 3MB of file size

		err := r.ParseMultipartForm(maxSize)
		if err != nil {
			log.Println(err)
			fmt.Fprintf(w, "Image too large. Max Size: %v", maxSize)
			return nil
		}

		file, fileHeader, err := r.FormFile("s3ProfileImage")
		if err != nil {
			log.Println(err)
			fmt.Fprintf(w, "Could not get uploaded file")
			return nil
		}
		defer file.Close()

		// create an AWS session which can be
		// reused if we're uploading many files
		s3, err := session.NewSession(&aws.Config{
			Region: aws.String("us-east-2"),
			Credentials: credentials.NewStaticCredentials(
				"secret-id",  // id
				"secret-key", // secret
				""),          // token can be left blank for now
		})
		if err != nil {
			fmt.Fprintf(w, "Could not upload file")
		}

		fileName, err := utility.S3Uploader(s3, file, fileHeader)
		if err != nil {
			fmt.Fprintf(w, "Could not upload file")
		}

		fmt.Fprintf(w, "Image uploaded successfully: %v", fileName)

		return nil
	} else {
		return c.Status(400).JSON(utility.Response{Status: 400, Message: utility.ErrInvalidUserID})
	}
}`

    I have integrated **adaptor** in GoFiber. After using it, I am unable to take build using "go build". It is throwing the below error.

# github.com/gofiber/fiber
..\..\pkg\mod\github.com\gofiber\fiber@v1.13.3\app.go:675:33: undefined: utils.MemoryTotal
..\..\pkg\mod\github.com\gofiber\fiber@v1.13.3\path.go:65:17: undefined: utils.GetTrimmedParam

Can you please help me to resolve the issue? What am I doing wrong here? I am new to golang and gofiber.

**Comment by tianjipeng** [comment]
Maybe you should use fiber v2. Plz check this repo release note

**Comment by vipinzco** [comment]
We are using fiber v2, already.
