### ISSUE TITLE
Adaptor does not respect multiple cookies in a response

### ISSUE THREAD

**Issue by Qolzam** [gofiber/adaptor#64]
If we add multiple cookies in a response, adaptor will [replace headers with the same name](https://github.com/gofiber/adaptor/blob/master/main.go#L122) using `w.Header().Set(string(k), string(v))`.

**Comment by arsmn** [comment]
It's fixed by [using Add instead of Set](https://github.com/gofiber/adaptor/commit/9b07027c9d0df28b92029831716e141b34203ce0)
